### ISSUE TITLE
nvprof is deprecated

### ISSUE THREAD

**Issue by Imss27** [puttsk/cuda-tutorial#11]
======== Warning: This version of nvprof doesn't support the underlying device, GPU profiling skipped
======== Warning: nvprof is not supported on devices with compute capability 8.0 and higher.
 
So I suggest an update of using another profiler.

**Comment by seung0h** [comment]
You could use `nsys nvprof` instead like `nsys nvprof ./vector_add` referred to the [official docs ](https://docs.nvidia.com/nsight-systems/UserGuide/index.html)of Nsight systems
